### ISSUE TITLE
[JA] Link to Chinese version document in japanese top page is broken.

### ISSUE THREAD

**Issue by miurahr** [tamlok/vnote-docs#2]
I18n feature breaks hyperlink in document.
It seems be a bug on japanese translation itself.

```
中国語 (简体中文)版を`ここ`_で見ることができます。
```

**Comment by tamlok** [comment]
btw, do we need to add a link to the japanese translation page?

**Comment by miurahr** [comment]
> btw, do we need to add a link to the japanese translation page?

Yes, you are right.
