### ISSUE TITLE
index.po and index.pot are outdated

### ISSUE THREAD

**Issue by miurahr** [tamlok/vnote-docs#8]
`user_docs/index.rst` has been udpated but `locale/<LANG>/index.po` is not. it should be updated.

We can define a work flow in several ways;

1.  PR for original text should include PO file updates. If not, don't merge it.
2. When text updates are commit, regenerate PO files automatically using CI/CD mechanism and push to master branch.
3. Sometimes update PO files by maintainer.

If maintainer want to use any translation web services, such as transifex, a maintainer need to upload PO files to the site when they are updated.  see https://docs.transifex.com/integrations/sphinx-doc/

**Comment by tamlok** [comment]
I think they can be updated by maintainer manually since it is not updated so frequently.
